print("/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\")
print("\n")
print("Name: Lexi")
print("Species: Dog")
print("Type: Mastiff/Black Lab")
print("Age: 8 years old")
print("Fun Fact: Plays 'keep away' instead of fetch, loves taking other peoples seats")
print("\n")
print("\t","\t","/\\/\\/\\/\\/\\/\\/\\/\\")
print("\n")
print("Name: Achilles")
print("Species: Dog")
print("Type: Bernese Mountain Dog")
print("Age: 7 years old")
print("Fun Fact: Is afraid of certain staircases in the house, thinks he is a lap dog")
print("\n")
print("\t","\t","/\\/\\/\\/\\/\\/\\/\\/\\")
print("\n")
print("Name: Arthur")
print("Species: Hedgehog")
print("Type: Unknown")
print("Age: 0 years old")
print("Fun Fact: Possibly not born yet, loves to cuddle")
print( "\n")
print("\t","\t","/\\/\\/\\/\\/\\/\\/\\/\\")
print("\n")
print("Name: Phoebe")
print("Species: Dog")
print("Type: Doberman")
print("Age: 8 or 9 years old")
print("Fun Fact: Lives in Trinidad, hates water and also sun")
print("\n")
print("\t","\t","/\\/\\/\\/\\/\\/\\/\\/\\")
print("\n")
print("Name: Bailey")
print("Species: Dog")
print("Type: German Shepherd")
print("Age: 7 years old")
print("Fun Fact: Lives in Trinidad, loves water, loves laying in the sun")
print("\n")
print("/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\")
